{
  "hash": "18d082f863b7db4921e88856c03cc6ad",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Predicting Health Conditions in Adults over 50 with Family Structure\"\nsubtitle: \"Systolic Blood Pressure and Diabetes\"\nauthor: \"Jose Diz Ferre and Reilly Burhanna\"\ndate: last-modified\nformat: \n  html:\n    toc: true\n    number-sections: true\n    code-fold: show\n    code-tools: true\n    code-overflow: wrap\n    embed-resources: true\n    date-format: iso\n    theme: spacelab\n---\n\n\n\n\n## R Packages and Setup {.unnumbered}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(comment = NA)\nlibrary(haven)\nlibrary(janitor) \nlibrary(naniar)\nlibrary(knitr)\nlibrary(dplyr)\nlibrary(broom)\nlibrary(car)\nlibrary(caret)\nlibrary(GGally)\nlibrary(gt)\nlibrary(gtsummary)\nlibrary(mice)\nlibrary(mosaic)\nlibrary(patchwork)\nlibrary(ROCR)\nlibrary(rsample)\nlibrary(rms)\nlibrary(cutpointr) \nlibrary(glue)\n\nlibrary(easystats)\nlibrary(tidyverse)\n\ntheme_set(theme_bw())\n```\n:::\n\n\n\n\n# Data Source\n\nThe data used for this study includes publicly released information from the Health and Retirement Study in 2022. The information can be downloaded by signing up for a free account using the link provided below. The information is gathered through questionnaires of adults over 50 years old and is repeated every two years to track participants as they age. Due to the wide range of information covered in this data, it is collected through a mixture of in person visits, online surveys, and phone calls.\n\nLink: <https://hrsdata.isr.umich.edu/data-products/2022-hrs-core>\n\nThe link provided above is also available in the resources below. Important sections within that webpage include the \"Data Description\" and \"Codebook\".\n\n# The Subjects\n\nThe population of this study includes residents of the United States who were born in the year 1971 or earlier and were questioned on numerous topics from health to family every 2 years, originally starting in 1992. Individuals were selected randomly from different geographic regions every 6 years which makes up cohorts of generations as well.\n\n# Loading and Tidying the Data\n\n## Loading the Raw Data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# <https://hrsdata.isr.umich.edu/data-products/2022-hrs-core>\n\nPhysMeasure_raw <- read_sas(\"C:/Users/dizferj/OneDrive - Cleveland Clinic/Documents/MPH/432/Data/h22core/h22sas/h22i_r.sas7bdat\") |>\n  zap_label() |>\n  distinct(HHID, .keep_all = TRUE)\n\nPhysHealth_raw <- read_sas(\"C:/Users/dizferj/OneDrive - Cleveland Clinic/Documents/MPH/432/Data/h22core/h22sas/h22c_r.sas7bdat\") |>\n  zap_label() |>\n  distinct(HHID, .keep_all = TRUE)\n\nFamStructH_raw <- read_sas(\"C:/Users/dizferj/OneDrive - Cleveland Clinic/Documents/MPH/432/Data/h22core/h22sas/h22e_h.sas7bdat\") |>\n  zap_label() |>\n  distinct(HHID, .keep_all = TRUE)\n\nFamStructMC_raw <- read_sas(\"C:/Users/dizferj/OneDrive - Cleveland Clinic/Documents/MPH/432/Data/h22core/h22sas/h22e_mc.sas7bdat\") |>\n  zap_label() |>\n  distinct(HHID, .keep_all = TRUE)\n\nDemographic_raw <- read_sas(\"C:/Users/dizferj/OneDrive - Cleveland Clinic/Documents/MPH/432/Data/h22core/h22sas/h22b_r.sas7bdat\") |>\n  zap_label() |>\n  distinct(HHID, .keep_all = TRUE)\n```\n:::\n\n\n\n\nOriginal data sets had some duplicate rows, which we removed above.\n\n## Cleaning the Data\n\n### Selecting Variables\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPhysMeasure <- PhysMeasure_raw |>\n  select(HHID, SI859) |>\n  rename(sbp = SI859) |>\n  janitor::clean_names()\n\nPhysHealth <- PhysHealth_raw |>\n  select(HHID, SC010) |>\n  rename(diabetes  = SC010) |>\n  janitor::clean_names()\n\nFamStructH <- FamStructH_raw |>\n  select(HHID, SE022, SE046) |>\n  rename(new_gchild = SE022, num_gchild = SE046) |>\n  janitor::clean_names()\n\nFamStructMC <- FamStructMC_raw |>\n  select(HHID, SE044) |>\n  rename(num_child = SE044) |>\n  janitor::clean_names()\n\nDemographic <- Demographic_raw |>\n  select(HHID, SB063) |>\n  rename(marital = SB063) |>\n  janitor::clean_names()\n```\n:::\n\n\n\n\n### Cleaning Outcome Data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPhysMeasure <- PhysMeasure |>\n  mutate(sbp = ifelse(sbp > 1 & sbp < 993, sbp, NA))\n\nPhysHealth <- PhysHealth |>\n  mutate(diabetes = ifelse(diabetes >= 1 & diabetes <= 6, diabetes, NA)) |>\n  mutate(diabetes = as.factor(diabetes)) |>\n  mutate(diabetes = diabetes |> \n           fct_recode(\"Yes\" = \"1\", \"Yes\" = \"6\", \"No\" = \"4\", \"No\" = \"5\"))\n```\n:::\n\n\n\n\n### Cleaning Predictor Data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFamStructH <- FamStructH |>\n  mutate(new_gchild = ifelse(new_gchild >= 1 & new_gchild <= 8, new_gchild, NA), \n         num_gchild = ifelse(num_gchild >= 0 & num_gchild <= 80, num_gchild, NA)) |>\n  mutate(new_gchild = as.factor(new_gchild)) |>\n  mutate(new_gchild = new_gchild |> \n           fct_recode(\"Yes\" = \"1\", \"No\" = \"5\", \"No\" = \"8\"))\n\nFamStructMC <- FamStructMC |>\n  mutate(num_child = ifelse(num_child >= 0 & num_child <= 20, num_child, NA))\n\nDemographic <- Demographic |>\n  mutate(marital = ifelse(marital >= 1 & marital <= 6, marital, NA)) |>\n  mutate(marital = as.factor(marital)) |>\n  mutate(marital = marital |> \n           fct_recode(\"Married\" = \"1\", \"Seperated\" = \"2\", \"Seperated\" = \"3\",\n                      \"Seperated\" = \"4\", \"Widowed\" = \"5\", \"Never Married\" = \"6\"))\n```\n:::\n\n\n\n\n### Combined Tibble\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp1 <- full_join(Demographic, FamStructH, by = \"hhid\")\ntemp2 <- full_join(temp1, FamStructMC, by = \"hhid\")\ntemp3 <- full_join(temp2, PhysMeasure, by = \"hhid\")\nPhysTibble <- full_join(temp3, PhysHealth, by = \"hhid\")\n\ndim(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11542     7\n```\n\n\n:::\n\n```{.r .cell-code}\nPhysTibble <- PhysTibble |> \n  drop_na()\n\ndim(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2231    7\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(432)\nPhysTibble <- PhysTibble |>\n  slice_sample(n=2000)\n\ndim(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2000    7\n```\n\n\n:::\n:::\n\n\n\n\nAs it can be seen above, we were able to filter for complete cases across all variables with more than enough samples left over. We then sampled the complete cases tibble for 2000 cases to meet the specifications. Originally we made two separate tibbles for our Linear and Logistic Regression. Although this would work, we have more than enough complete cases to study the the same sample of people for both models. This might be interesting considering both models use the same inputs to predict a physical health outcome, so we decided on a combined tibble containing both outcomes.\n\n# The Tidy Tibble\n\n## Listing the Tibble\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPhysTibble\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,000 × 7\n   hhid   marital   new_gchild num_gchild num_child   sbp diabetes\n   <chr>  <fct>     <fct>           <dbl>     <dbl> <dbl> <fct>   \n 1 050380 Widowed   No                  5         2   153 Yes     \n 2 501961 Married   No                 16         0   107 Yes     \n 3 543841 Seperated Yes                21         2   164 No      \n 4 014092 Widowed   No                  4         3   154 No      \n 5 022335 Widowed   No                  9         3   137 No      \n 6 537264 Married   Yes                 6         1   142 No      \n 7 903224 Seperated No                  9         1   136 Yes     \n 8 500094 Married   No                  4         2   153 No      \n 9 062157 Widowed   No                 10         1   133 No      \n10 077723 Widowed   No                  5         3   142 No      \n# ℹ 1,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\n## Size and Identifiers\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2000    7\n```\n\n\n:::\n\n```{.r .cell-code}\nn_distinct(PhysTibble$hhid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2000\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(PhysTibble$hhid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n\n\nOur final tibble has 2000 samples with 7 variables: an identifier, four predictors, and two outcomes. The identifier is defined as a character in R and is named hhid. It has 2000 distinct values which matches the sample size of our final tibble. \n\n## Save The Tibble\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(PhysTibble, file = \"PhysTibble_reillyJose.Rds\")\n```\n:::\n\n\n\n\n# The Code Book\n\n## Defining the Variables\n\nVariable | Role | Type | Description\n:------: | :----: | :----: | :---------------:\n`hhid` | Identifier | - | character code for respondents\n`marital` | Input | 4-cat | Marital Status (Married, Separated, Widowed, Never Married)\n`new_gchild` | Input | 2-cat | Any new grandchildren in past 2 years (Yes/No)\n`num_gchild` | Input | quant | Number of grandchildren of respondent\n`num_child` | Input | quant | Number of children of respondent\n`sbp` | Outcome (linear) | quant | Measured Systolic Blood Pressure (mmHg)\n`diabetes` | Outcome (logistic) | 2-cat | Have or had Diabetes or High Blood Pressure (Yes/No)\n\n## Numerical Description\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_codebook(PhysTibble, max_values = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPhysTibble (2000 rows and 7 variables, 7 shown)\n\nID | Name       | Type        | Missings |        Values |            N\n---+------------+-------------+----------+---------------+-------------\n1  | hhid       | character   | 0 (0.0%) |        010038 |    1 ( 0.0%)\n   |            |             |          |        010059 |    1 ( 0.0%)\n   |            |             |          |        010451 |    1 ( 0.0%)\n   |            |             |          |         (...) |             \n---+------------+-------------+----------+---------------+-------------\n2  | marital    | categorical | 0 (0.0%) |       Married |  837 (41.9%)\n   |            |             |          |     Seperated |  466 (23.3%)\n   |            |             |          |       Widowed |  570 (28.5%)\n   |            |             |          | Never Married |  127 ( 6.3%)\n---+------------+-------------+----------+---------------+-------------\n3  | new_gchild | categorical | 0 (0.0%) |           Yes |  402 (20.1%)\n   |            |             |          |            No | 1598 (79.9%)\n---+------------+-------------+----------+---------------+-------------\n4  | num_gchild | numeric     | 0 (0.0%) |       [0, 45] |         2000\n---+------------+-------------+----------+---------------+-------------\n5  | num_child  | numeric     | 0 (0.0%) |       [0, 20] |         2000\n---+------------+-------------+----------+---------------+-------------\n6  | sbp        | numeric     | 0 (0.0%) |     [74, 232] |         2000\n---+------------+-------------+----------+---------------+-------------\n7  | diabetes   | categorical | 0 (0.0%) |           Yes |  661 (33.1%)\n   |            |             |          |            No | 1339 (67.0%)\n-----------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n\n\n# Linear Regression Plans\n\n## My First Research Question\n\nDoes an increased presence of children and grandchildren directly affect a person's Systolic Blood Pressure while accounting for marital status?\n\n## My Quantitative Outcome\n\nOur quantitative outcome is named `sbp` in our final tibble. We are interested in this variable since adults over 50 have an increased risk of high Systolic Blood Pressure (SBP). We were interested in seeing if family structure data, such as marital status and the number direct descendants of a person, result in lower SBP measurements for survey respondents. All rows of our final tibble contain complete data on `sbp`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_distinct(PhysTibble$sbp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\nbw = 2 \nplot1 <- ggplot(PhysTibble, aes(x = sbp)) +                     \n  geom_histogram(binwidth = bw, fill = \"black\", col = \"white\") + \n  stat_function(fun = function(x)                               \n    dnorm(x, mean = mean(PhysTibble$sbp, na.rm = TRUE),         \n          sd = sd(PhysTibble$sbp, na.rm = TRUE)) * \n          length(PhysTibble$sbp) * bw,\n    geom = \"area\", alpha = 0.5, \n    fill = \"lightblue\", col = \"blue\") +                         \n  labs(x = \"Systolic Blood Pressure (SBP)\", y = \"Count\")\n\nplot2 <- ggplot(PhysTibble, aes(sample = sbp)) +\n  geom_qq(color = \"black\") +\n  geom_qq_line(color = \"blue\") +\n  theme_minimal() +\n  theme(panel.grid = element_blank()) +\n  labs(x = \"Theoretical Quantiles\", y = \"Sample Quantiles\")\n\nplot1 + plot2 +\n  plot_annotation(title = \"Simple Visualizations of Distribution of Systolic Blood Presure\",\n                  subtitle = \"Histogram and Q-Q Plot\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\nThe plot above shows the distribution of sbp measurements in this sample is relatively symmetric and therefore almost continuous. The fitted normal curve models the distribution well suggesting a transform is most likely not necessary. Using the \"n_distinct\" function it can be seen that `sbp` has 120 different values which meets the specifications. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(PhysTibble$sbp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPhysTibble$sbp \n       n  missing distinct     Info     Mean  pMedian      Gmd      .05 \n    2000        0      120        1    130.7      130    22.87      101 \n     .10      .25      .50      .75      .90      .95 \n     106      117      129      143      158      167 \n\nlowest :  74  79  81  83  84, highest: 206 207 213 223 232\n```\n\n\n:::\n\n```{.r .cell-code}\nfavstats(PhysTibble$sbp) |> gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uqcxpsyqyw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uqcxpsyqyw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uqcxpsyqyw thead, #uqcxpsyqyw tbody, #uqcxpsyqyw tfoot, #uqcxpsyqyw tr, #uqcxpsyqyw td, #uqcxpsyqyw th {\n  border-style: none;\n}\n\n#uqcxpsyqyw p {\n  margin: 0;\n  padding: 0;\n}\n\n#uqcxpsyqyw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uqcxpsyqyw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uqcxpsyqyw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uqcxpsyqyw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uqcxpsyqyw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uqcxpsyqyw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uqcxpsyqyw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uqcxpsyqyw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uqcxpsyqyw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uqcxpsyqyw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uqcxpsyqyw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uqcxpsyqyw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uqcxpsyqyw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uqcxpsyqyw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uqcxpsyqyw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqcxpsyqyw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uqcxpsyqyw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uqcxpsyqyw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uqcxpsyqyw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqcxpsyqyw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uqcxpsyqyw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqcxpsyqyw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uqcxpsyqyw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqcxpsyqyw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uqcxpsyqyw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqcxpsyqyw .gt_left {\n  text-align: left;\n}\n\n#uqcxpsyqyw .gt_center {\n  text-align: center;\n}\n\n#uqcxpsyqyw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uqcxpsyqyw .gt_font_normal {\n  font-weight: normal;\n}\n\n#uqcxpsyqyw .gt_font_bold {\n  font-weight: bold;\n}\n\n#uqcxpsyqyw .gt_font_italic {\n  font-style: italic;\n}\n\n#uqcxpsyqyw .gt_super {\n  font-size: 65%;\n}\n\n#uqcxpsyqyw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uqcxpsyqyw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uqcxpsyqyw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uqcxpsyqyw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uqcxpsyqyw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uqcxpsyqyw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uqcxpsyqyw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uqcxpsyqyw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uqcxpsyqyw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min\">min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Q1\">Q1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Q3\">Q3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"max\">max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing\">missing</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"min\" class=\"gt_row gt_right\">74</td>\n<td headers=\"Q1\" class=\"gt_row gt_right\">117</td>\n<td headers=\"median\" class=\"gt_row gt_right\">129</td>\n<td headers=\"Q3\" class=\"gt_row gt_right\">143</td>\n<td headers=\"max\" class=\"gt_row gt_right\">232</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">130.7185</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">20.60861</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"missing\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nPhysTibble |>\n  tabyl(sbp) |>\n  adorn_pct_formatting() |> \n  arrange(desc(n)) |>\n  head(5) |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"atcxvltsiq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#atcxvltsiq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#atcxvltsiq thead, #atcxvltsiq tbody, #atcxvltsiq tfoot, #atcxvltsiq tr, #atcxvltsiq td, #atcxvltsiq th {\n  border-style: none;\n}\n\n#atcxvltsiq p {\n  margin: 0;\n  padding: 0;\n}\n\n#atcxvltsiq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#atcxvltsiq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#atcxvltsiq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#atcxvltsiq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#atcxvltsiq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#atcxvltsiq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#atcxvltsiq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#atcxvltsiq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#atcxvltsiq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#atcxvltsiq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#atcxvltsiq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#atcxvltsiq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#atcxvltsiq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#atcxvltsiq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#atcxvltsiq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atcxvltsiq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#atcxvltsiq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#atcxvltsiq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#atcxvltsiq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atcxvltsiq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#atcxvltsiq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atcxvltsiq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#atcxvltsiq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atcxvltsiq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#atcxvltsiq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atcxvltsiq .gt_left {\n  text-align: left;\n}\n\n#atcxvltsiq .gt_center {\n  text-align: center;\n}\n\n#atcxvltsiq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#atcxvltsiq .gt_font_normal {\n  font-weight: normal;\n}\n\n#atcxvltsiq .gt_font_bold {\n  font-weight: bold;\n}\n\n#atcxvltsiq .gt_font_italic {\n  font-style: italic;\n}\n\n#atcxvltsiq .gt_super {\n  font-size: 65%;\n}\n\n#atcxvltsiq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#atcxvltsiq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#atcxvltsiq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#atcxvltsiq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#atcxvltsiq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#atcxvltsiq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#atcxvltsiq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#atcxvltsiq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#atcxvltsiq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sbp\">sbp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"percent\">percent</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"sbp\" class=\"gt_row gt_right\">130</td>\n<td headers=\"n\" class=\"gt_row gt_right\">57</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">2.9%</td></tr>\n    <tr><td headers=\"sbp\" class=\"gt_row gt_right\">136</td>\n<td headers=\"n\" class=\"gt_row gt_right\">50</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">2.5%</td></tr>\n    <tr><td headers=\"sbp\" class=\"gt_row gt_right\">126</td>\n<td headers=\"n\" class=\"gt_row gt_right\">48</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">2.4%</td></tr>\n    <tr><td headers=\"sbp\" class=\"gt_row gt_right\">127</td>\n<td headers=\"n\" class=\"gt_row gt_right\">47</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">2.4%</td></tr>\n    <tr><td headers=\"sbp\" class=\"gt_row gt_right\">119</td>\n<td headers=\"n\" class=\"gt_row gt_right\">45</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">2.2%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThe tables above show that sbp has a mean of around 130 mmHg, which is close to the highest percentage instance of sbp. This value makes up 2.9% of the outcome data for these 2000 samples which is below the 10% threshold.\n\n## My Planned Predictors (Linear Model)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_distinct(PhysTibble$num_gchild)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 34\n```\n\n\n:::\n\n```{.r .cell-code}\nn_distinct(PhysTibble$num_child)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary_table <- PhysTibble |> \n  select(new_gchild, marital) |> \n  map_df(~ tabyl(.) |> adorn_totals(\"row\"), .id = \"Variable\") \n\nsummary_table |> \n  gt() |> \n  tab_header(title = \"Summary of Categorical Variables\") |> \n  fmt_number(columns = c(\"percent\"), decimals = 3) |> \n  cols_label(n = \"Count\", percent = \"Percent\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ccgxpwovdu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ccgxpwovdu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ccgxpwovdu thead, #ccgxpwovdu tbody, #ccgxpwovdu tfoot, #ccgxpwovdu tr, #ccgxpwovdu td, #ccgxpwovdu th {\n  border-style: none;\n}\n\n#ccgxpwovdu p {\n  margin: 0;\n  padding: 0;\n}\n\n#ccgxpwovdu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ccgxpwovdu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ccgxpwovdu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ccgxpwovdu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ccgxpwovdu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ccgxpwovdu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ccgxpwovdu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ccgxpwovdu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ccgxpwovdu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ccgxpwovdu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ccgxpwovdu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ccgxpwovdu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ccgxpwovdu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ccgxpwovdu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ccgxpwovdu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ccgxpwovdu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ccgxpwovdu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ccgxpwovdu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ccgxpwovdu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ccgxpwovdu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ccgxpwovdu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ccgxpwovdu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ccgxpwovdu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ccgxpwovdu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ccgxpwovdu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ccgxpwovdu .gt_left {\n  text-align: left;\n}\n\n#ccgxpwovdu .gt_center {\n  text-align: center;\n}\n\n#ccgxpwovdu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ccgxpwovdu .gt_font_normal {\n  font-weight: normal;\n}\n\n#ccgxpwovdu .gt_font_bold {\n  font-weight: bold;\n}\n\n#ccgxpwovdu .gt_font_italic {\n  font-style: italic;\n}\n\n#ccgxpwovdu .gt_super {\n  font-size: 65%;\n}\n\n#ccgxpwovdu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ccgxpwovdu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ccgxpwovdu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ccgxpwovdu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ccgxpwovdu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ccgxpwovdu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ccgxpwovdu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ccgxpwovdu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ccgxpwovdu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Summary of Categorical Variables</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Variable\">Variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a.\">.</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">Count</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"percent\">Percent</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">new_gchild</td>\n<td headers=\".\" class=\"gt_row gt_center\">Yes</td>\n<td headers=\"n\" class=\"gt_row gt_right\">402</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">0.201</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">new_gchild</td>\n<td headers=\".\" class=\"gt_row gt_center\">No</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1598</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">0.799</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">new_gchild</td>\n<td headers=\".\" class=\"gt_row gt_center\">Total</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">1.000</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">marital</td>\n<td headers=\".\" class=\"gt_row gt_center\">Married</td>\n<td headers=\"n\" class=\"gt_row gt_right\">837</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">0.418</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">marital</td>\n<td headers=\".\" class=\"gt_row gt_center\">Seperated</td>\n<td headers=\"n\" class=\"gt_row gt_right\">466</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">0.233</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">marital</td>\n<td headers=\".\" class=\"gt_row gt_center\">Widowed</td>\n<td headers=\"n\" class=\"gt_row gt_right\">570</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">0.285</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">marital</td>\n<td headers=\".\" class=\"gt_row gt_center\">Never Married</td>\n<td headers=\"n\" class=\"gt_row gt_right\">127</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">0.064</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">marital</td>\n<td headers=\".\" class=\"gt_row gt_center\">Total</td>\n<td headers=\"n\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"percent\" class=\"gt_row gt_right\">1.000</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nWe have four predictors total as shown in the codebook above. The two that are quantitative are `num_gchild` and `num_child` with 34 and 13 distinct values respectively. Our categorical variables are `new_gchild`, which is binary, and `marital` which is four levels. The table above shows greater than 30 observations for each variable. Our outcome `sbp` has no missing data and therefore the candidate predictors must not be any bigger than 4 + (2000-100)/100 = 23. With only four predictors, we are well below this threshold.\n\n### Model Expectations\n\nWe expect to see lower Systolic Blood Pressure (SBP) Levels in those with more grandchildren and those who recently had grand children. For direct children we expect to see a similar outcome as to grandchildren, but possibly not as strong. We also believe there might be an association between SBP and the marital status of a person, while expecting a difference between those who are married and those who are separated.\n\n### Missingness Summary\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmiss_var_summary(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  variable   n_miss pct_miss\n  <chr>       <int>    <num>\n1 hhid            0        0\n2 marital         0        0\n3 new_gchild      0        0\n4 num_gchild      0        0\n5 num_child       0        0\n6 sbp             0        0\n7 diabetes        0        0\n```\n\n\n:::\n\n```{.r .cell-code}\nmiss_case_table(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  n_miss_in_case n_cases pct_cases\n           <int>   <int>     <dbl>\n1              0    2000       100\n```\n\n\n:::\n:::\n\n\n\n\nFrom the summaries above it can be seen that we have absolutely no missing data. This is explained above in the data cleaning section.\n\n# Logistic Regression Plans\n\n## My Second Research Question\n\nIs there an increased risk for diabetes in those with either less children or grandchildren and how does this change when factoring in a person's current marital status?\n\n## My Binary Outcome\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPhysTibble |> tabyl(diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n diabetes    n percent\n      Yes  661  0.3305\n       No 1339  0.6695\n```\n\n\n:::\n:::\n\n\n\n\nOur binary outcome is called `diabetes` which is a yes or no answer to whether the person aged over 50 has had diabetes in their life. The table above shows that almost one third of the sample has answered yes.\n\n## My Planned Predictors (Logistic Model)\n\nThe predictors here are the same as listed in the linear model section: `num_gchild`, `num_child`, `new_gchild`, and `marital`. N2 would be 661 since the \"Yes\" group is smaller. This means our model can have no more than 4+(661-100)/100 = 9 predictors, which is well beyond the planned count of four predictors for this analysis.\n\n### Model Expectations\n\nWe expect to see a positive association between those with more grandchildren and children and not having diabetes. We do not have a good guess for the association between marital status and diabetes, but we do assume that the results might align with our Linear Model's association with Systolic Blood Pressure. Children and grandchildren can take time out of a person's life, so it will be interesting to see if that time spent is positively associated with better health.\n\n### Anticipated Direction of Effects\n\nI expect higher blood pressure risk to be associated with widowed status, with no new grand children, a lower number of children or grand children.\n\n### Missingness Summary\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmiss_var_summary(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  variable   n_miss pct_miss\n  <chr>       <int>    <num>\n1 hhid            0        0\n2 marital         0        0\n3 new_gchild      0        0\n4 num_gchild      0        0\n5 num_child       0        0\n6 sbp             0        0\n7 diabetes        0        0\n```\n\n\n:::\n\n```{.r .cell-code}\nmiss_case_table(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  n_miss_in_case n_cases pct_cases\n           <int>   <int>     <dbl>\n1              0    2000       100\n```\n\n\n:::\n:::\n\n\n\n\nFrom the summaries above it can be seen that we have absolutely no missing data. This is explained above in the data cleaning section where we chose working with complete cases.\n\n- We have complete data for all of the logistic model predictors in 2000 (100%) of the 2000 rows in my data.\n- We are missing XX values (XX%) for (insert variable name here) (optional with imputation)\n\n# Linear Regression Analyses\n\nFollow the Project A instructions.\n\n## Missingness\n\nWe will work with complete cases since missing data was dropped in the data cleaning section.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmiss_var_summary(PhysTibble)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  variable   n_miss pct_miss\n  <chr>       <int>    <num>\n1 hhid            0        0\n2 marital         0        0\n3 new_gchild      0        0\n4 num_gchild      0        0\n5 num_child       0        0\n6 sbp             0        0\n7 diabetes        0        0\n```\n\n\n:::\n:::\n\n\n\n\n### Single Imputation Approach (optional)\n\n\nPhysTibble_i <- \n  mice(PhysTibble, m = 1, seed = 432432, print = FALSE) |>\n  complete() |>\n  tibble()\n\nn_miss(PhysTibble_i)\n\n\n## Outcome Transformation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_temp <- lm(sbp ~ num_gchild + new_gchild + marital + num_child, data = PhysTibble)\n\nboxCox(mod_temp)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\nPhysTibble <- PhysTibble |>\n  mutate(logsbp = log(sbp))\n\np1 <- ggplot(PhysTibble, aes(sample = logsbp)) +\n  geom_qq(col = \"navy\") + geom_qq_line(col = \"red\") + \n  labs(title = \"Normal Q-Q plot of log(sbp)\", x = \"\",\n       y = \"Log of SBP Cholesterol Level (mmHg)\")\n\np2 <- ggplot(PhysTibble, aes(x = logsbp)) +\n  geom_histogram(bins = 20, col = \"white\", fill = \"navy\") +\n  labs(title = \"Histogram of log(sbp)\", x = \"Log of SBP Cholesterol Level (mmHg)\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n:::\n\n\n\n\n\n## Scatterplot Matrix and Collinearity\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggpairs(PhysTibble, columns = c(\"num_gchild\", \"new_gchild\", \"marital\", \n                               \"num_child\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmod_A <- lm(sbp ~ num_gchild + new_gchild + marital + num_child, data = PhysTibble)\n\ncar::vif(mod_A)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               GVIF Df GVIF^(1/(2*Df))\nnum_gchild 1.174037  1        1.083530\nnew_gchild 1.026832  1        1.013327\nmarital    1.041998  3        1.006880\nnum_child  1.177227  1        1.085001\n```\n\n\n:::\n:::\n\n\n\n\n\n## Model A\n\n### Fitting Model A\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_A <- lm(logsbp ~ num_gchild + new_gchild + marital + num_child, data = PhysTibble)\n\ndd <- datadist(PhysTibble)\noptions(datadist = \"dd\")\n\nmod_A_ols <- ols(logsbp ~ num_gchild + new_gchild + marital + num_child,\n                 data = PhysTibble, x = TRUE, y = TRUE)\n```\n:::\n\n\n\n\n\n### Tidied Coefficient Estimates (Model A)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(mod_A, ci = 0.90) |> print_md(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Parameter               | Coefficient |        SE |              90% CI | t(1993) |      p |\n|:-----------------------|:-----------:|:---------:|:-------------------:|:-------:|:------:|\n|(Intercept)             |       4.827 |     0.010 |      (4.810, 4.843) | 481.141 | < .001 |\n|num gchild              |   7.522e-04 | 7.662e-04 | (-5.086e-04, 0.002) |   0.982 | 0.326  |\n|new gchild (No)         |       0.023 |     0.009 |      (0.009, 0.038) |   2.672 | 0.008  |\n|marital (Seperated)     |      -0.002 |     0.009 |     (-0.017, 0.013) |  -0.210 | 0.834  |\n|marital (Widowed)       |       0.012 |     0.009 |     (-0.002, 0.026) |   1.359 | 0.174  |\n|marital (Never Married) |       0.006 |     0.015 |     (-0.018, 0.031) |   0.415 | 0.678  |\n|num child               |       0.004 |     0.002 | (-8.335e-05, 0.007) |   1.608 | 0.108  |\n\n\n:::\n:::\n\n\n\n\n\n### Summarizing Fit (Model A)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(summary(mod_A_ols, conf.int = 0.90))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(mod_A_ols, conf.int = 0.90) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|                                | Low| High| Diff.| Effect|  S.E.| Lower 0.9| Upper 0.9| Type|\n|:-------------------------------|---:|----:|-----:|------:|-----:|---------:|---------:|----:|\n|num_gchild                      |   3|    8|     5|  0.004| 0.004|    -0.003|     0.010|    1|\n|num_child                       |   1|    3|     2|  0.007| 0.004|     0.000|     0.015|    1|\n|new_gchild - Yes:No             |   2|    1|    NA| -0.023| 0.009|    -0.038|    -0.009|    1|\n|marital - Seperated:Married     |   1|    2|    NA| -0.002| 0.009|    -0.017|     0.013|    1|\n|marital - Widowed:Married       |   1|    3|    NA|  0.012| 0.009|    -0.002|     0.026|    1|\n|marital - Never Married:Married |   1|    4|    NA|  0.006| 0.015|    -0.018|     0.031|    1|\n\n\n:::\n\n```{.r .cell-code}\nmodel_performance(mod_A) |> print_md(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\nTable: Indices of model performance\n\n|AIC       |      AICc |       BIC |    R2 | R2 (adj.) |  RMSE | Sigma |\n|:---------|:---------:|:---------:|:-----:|:---------:|:-----:|:-----:|\n|-1762.165 | -1762.093 | -1717.358 | 0.009 |     0.006 | 0.155 | 0.155 |\n\n\n:::\n\n```{.r .cell-code}\nglance(mod_A) |>\n  select(r2 = r.squared, adjr2 = adj.r.squared, sigma, \n         AIC, BIC, nobs, df, df.residual) |>\n  kable(digits = c(3, 3, 2, 1, 1, 0, 0, 0))\n```\n\n::: {.cell-output-display}\n\n\n|    r2| adjr2| sigma|     AIC|     BIC| nobs| df| df.residual|\n|-----:|-----:|-----:|-------:|-------:|----:|--:|-----------:|\n| 0.009| 0.006|  0.16| -1762.2| -1717.4| 2000|  6|        1993|\n\n\n:::\n:::\n\n\n\n\n\n### Regression Diagnostics (Model A)\n\nFor the most part, these plots look very reasonable. I see no clear problems with the assumptions of linearity, normality or constant variance evident in any of these results.\n\nThe main issue is the posterior predictive check, where our predictions are missing on the left part of the center of the distribution, with more predicted values of log(HDL) in the 112.5 to 125 range than we see in the original data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(mod_A, detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\n## Non-Linearity\n\nHere’s the relevant Spearman \n plot, as a place to look for sensible places to consider a non-linear term or terms.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(spearman2(logsbp ~ num_gchild + new_gchild + marital + num_child, data = PhysTibble))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\nOur Spearman plot first suggests the use of a non-linear term in new_gchild, so we’ll add a restricted cubic spline in new_gchild using 5 knots, which should add 3 degrees of freedom to our initial model.\n\nNext, the num_gchild variable also seems to be a good choice, so we’ll add an interaction between num_gchild and the main effect of new_gchild, which will add one more degree of freedom to our model A.\n\n## Model B\n\nOur Model B will add two non-linear terms, summing up to 4 additional degrees of freedom, to our model A.\n\n### Fitting Model B\n\nWe’ll also fit model B with the ols() function from the rms package.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_B <- lm(logsbp ~ rcs(num_gchild, 5) + new_gchild + num_gchild %ia% new_gchild + marital, data = PhysTibble)\n\ndd <- datadist(PhysTibble)\noptions(datadist = \"dd\")\n\nmod_B_ols <- ols(logsbp ~ rcs(num_gchild, 5) + new_gchild + num_gchild %ia% new_gchild + marital,\n            data = PhysTibble, x = TRUE, y = TRUE)\n```\n:::\n\n\n\n\n\n### Tidied Coefficient Estimates (Model B)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(mod_B, conf.int = TRUE, conf.level = 0.90) |>\n  select(term, estimate, se = std.error, \n         low90 = conf.low, high90 = conf.high, \n         p = p.value) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term                            | estimate|    se|  low90| high90|     p|\n|:-------------------------------|--------:|-----:|------:|------:|-----:|\n|(Intercept)                     |    4.826| 0.022|  4.789|  4.863| 0.000|\n|rcs(num_gchild, 5)num_gchild    |    0.003| 0.010| -0.013|  0.019| 0.748|\n|rcs(num_gchild, 5)num_gchild'   |   -0.014| 0.158| -0.275|  0.247| 0.930|\n|rcs(num_gchild, 5)num_gchild''  |    0.044| 0.399| -0.613|  0.701| 0.912|\n|rcs(num_gchild, 5)num_gchild''' |   -0.055| 0.311| -0.567|  0.456| 0.859|\n|new_gchildNo                    |    0.016| 0.014| -0.007|  0.039| 0.252|\n|num_gchild %ia% new_gchild      |    0.001| 0.002| -0.002|  0.004| 0.474|\n|maritalSeperated                |    0.000| 0.009| -0.015|  0.014| 0.965|\n|maritalWidowed                  |    0.011| 0.009| -0.003|  0.025| 0.189|\n|maritalNever Married            |    0.008| 0.015| -0.016|  0.033| 0.573|\n\n\n:::\n:::\n\n\n\n\n\n### Effects Plot for Model B\n\nHere, we use the mod_B_ols model to look at the effects using its plot and associated table, which may be especially helpful when we include non-linear terms.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(summary(mod_B_ols, conf.int = 0.90))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(mod_B_ols, conf.int = 0.90) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|                                | Low| High| Diff.| Effect|  S.E.| Lower 0.9| Upper 0.9| Type|\n|:-------------------------------|---:|----:|-----:|------:|-----:|---------:|---------:|----:|\n|num_gchild                      |   3|    8|     5|  0.018| 0.010|     0.002|     0.035|    1|\n|new_gchild - Yes:No             |   2|    1|    NA| -0.022| 0.009|    -0.037|    -0.007|    1|\n|marital - Seperated:Married     |   1|    2|    NA|  0.000| 0.009|    -0.015|     0.014|    1|\n|marital - Widowed:Married       |   1|    3|    NA|  0.011| 0.009|    -0.003|     0.025|    1|\n|marital - Never Married:Married |   1|    4|    NA|  0.008| 0.015|    -0.016|     0.033|    1|\n\n\n:::\n:::\n\n\n\n\n\n### Summarizing Fit (Model B)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(mod_B) |>\n  select(r2 = r.squared, adjr2 = adj.r.squared, sigma, \n         AIC, BIC, nobs, df, df.residual) |>\n  kable(digits = c(3, 3, 2, 1, 1, 0, 0, 0))\n```\n\n::: {.cell-output-display}\n\n\n|   r2| adjr2| sigma|     AIC|   BIC| nobs| df| df.residual|\n|----:|-----:|-----:|-------:|-----:|----:|--:|-----------:|\n| 0.01| 0.005|  0.16| -1758.6| -1697| 2000|  9|        1990|\n\n\n:::\n:::\n\n\n\n\n\n### Regression Diagnostics (Model B)\n\nThese residual plots look reasonable. I see no clear problems with the assumptions of normality or constant variance evident in these results. Slight issues with linearity and heteroskedasticity are present on the left parts of the graphs. The posterior predictive check seems simital to Model A. The collinearity we’ve introduced here is due to the interaction terms, so that’s not a concern for us.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(mod_B, detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Validating Models A and B\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4321); (valA <- validate(mod_A_ols))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          index.orig training   test optimism index.corrected  n\nR-square      0.0085   0.0125 0.0048   0.0077          0.0008 40\nMSE           0.0241   0.0241 0.0242  -0.0001          0.0241 40\ng             0.0160   0.0190 0.0140   0.0050          0.0110 40\nIntercept     0.0000   0.0000 1.1130  -1.1130          1.1130 40\nSlope         1.0000   1.0000 0.7710   0.2290          0.7710 40\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(4322); (valB <- validate(mod_B_ols))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          index.orig training   test optimism index.corrected  n\nR-square      0.0097   0.0143 0.0030   0.0113         -0.0016 40\nMSE           0.0240   0.0242 0.0242   0.0000          0.0240 40\ng             0.0174   0.0201 0.0129   0.0073          0.0102 40\nIntercept     0.0000   0.0000 1.6476  -1.6476          1.6476 40\nSlope         1.0000   1.0000 0.6611   0.3389          0.6611 40\n```\n\n\n:::\n:::\n\n\n\n\n\n### Validated $R^2$ statistics, and MSE as well as IC statistics\n\nC = 0.5 + Dxy/2\n\nModel | Validated $R^2$ | validated MSR | AIC | BIC | df\n-----: | -------- | -------- | -------- | -------- | --------\nA |  0.0008 |  0.0241 | -1762.2\t| -1717.4\t | 6\nB | -0.0016 | 0.024 | -1758.6 |\t-1697 | 9\n\n## Final Linear Regression Model\n\nWe’ll choose Model A here.\n\nWe see worse numbers for Model B in terms of validated and validated MSR. Model A matches the assumptions of linear regression better. Given the negative R2 value of model b, we will definitly pick model a.\n\n### Winning Model's Parameter Estimates\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_A_ols\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear Regression Model\n\nols(formula = logsbp ~ num_gchild + new_gchild + marital + num_child, \n    data = PhysTibble, x = TRUE, y = TRUE)\n\n                Model Likelihood    Discrimination    \n                      Ratio Test           Indexes    \nObs    2000    LR chi2     17.15    R2       0.009    \nsigma0.1554    d.f.            6    R2 adj   0.006    \nd.f.   1993    Pr(> chi2) 0.0087    g        0.016    \n\nResiduals\n\n       Min         1Q     Median         3Q        Max \n-0.5755729 -0.0998415 -0.0008637  0.1035361  0.6078322 \n\n                      Coef    S.E.   t      Pr(>|t|)\nIntercept              4.8268 0.0100 481.14 <0.0001 \nnum_gchild             0.0008 0.0008   0.98 0.3263  \nnew_gchild=No          0.0235 0.0088   2.67 0.0076  \nmarital=Seperated     -0.0019 0.0090  -0.21 0.8340  \nmarital=Widowed        0.0116 0.0085   1.36 0.1743  \nmarital=Never Married  0.0062 0.0149   0.41 0.6782  \nnum_child              0.0036 0.0022   1.61 0.1079  \n```\n\n\n:::\n:::\n\n\n\n\n\n### Effects Plot for Winning Model\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(summary(mod_A_ols, conf.int = 0.90))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Numerical Description of Effect Sizes\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod_A_ols, conf.int = 0.90) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|                                | Low| High| Diff.| Effect|  S.E.| Lower 0.9| Upper 0.9| Type|\n|:-------------------------------|---:|----:|-----:|------:|-----:|---------:|---------:|----:|\n|num_gchild                      |   3|    8|     5|  0.004| 0.004|    -0.003|     0.010|    1|\n|num_child                       |   1|    3|     2|  0.007| 0.004|     0.000|     0.015|    1|\n|new_gchild - Yes:No             |   2|    1|    NA| -0.023| 0.009|    -0.038|    -0.009|    1|\n|marital - Seperated:Married     |   1|    2|    NA| -0.002| 0.009|    -0.017|     0.013|    1|\n|marital - Widowed:Married       |   1|    3|    NA|  0.012| 0.009|    -0.002|     0.026|    1|\n|marital - Never Married:Married |   1|    4|    NA|  0.006| 0.015|    -0.018|     0.031|    1|\n\n\n:::\n:::\n\n\n\n\n\nNew grandchildren description: If we have two subjects of the same marital status, number of grandchildren and number of children, then if subject 1 does not have a new grandchildren and subject 2 does have a newgrand children, then our model estimates that subject 1 will have a log(sbp) that is 0.023 higher than subject 2 on average. The 90% confidence interval around that estimated effect on log(sbp) ranges from (0.0091, 0.038).\n\n\n### Nomogram of Winning Model\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Predict(mod_A_ols))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(nomogram(mod_A_ols, fun = exp, funlabel = \"SBP\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-34-2.png){width=672}\n:::\n:::\n\n\n\n\n\n### Prediction for a New Subject\n\nHere, I’ll actually run two predictions, one for a subject with (1) and without (2) new_gchild with the same values of num_child (2), num_gchild (5) and marital status (widowed).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_subjects <- data.frame(num_child = c(2, 2), num_gchild = c(5, 5),\n             marital = c(\"Widowed\", \"Widowed\"), new_gchild = c(\"Yes\", \"No\"))\n\npreds1 <- predict.lm(mod_A, newdata = new_subjects, \n                     interval = \"prediction\", level = 0.90)\n\nexp(preds1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit       lwr      upr\n1 127.6623  98.79885 164.9580\n2 130.6952 101.17939 168.8213\n```\n\n\n:::\n:::\n\n\n\n\n\n# Logistic Regression Analyses\n\n## Missingness\n\n\n\nAs explained in the data cleaning and 8.1.1 sections, we will work with complete cases and no missing data.\n\n- We have complete data for all of the logistic model predictors in 2000 (100%) of the 2000 rows in my data.\n\nAgain, we’ll assume missing values are MAR, and use the single imputation approach developed previously in Section 8.1.1. (optional)\n- We are missing XX values (XX%) for insert (variable name here). (optional with imputation)\n\n## Model Y\n\nWe’ll predict Pr(diabetes = 1), the probability of having a low enough risk of diabetes to put the subject at risk, as a function of num_gchild, new_gchild, marital, and num_child.\n\n### Fitting Model Y\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_Y <- glm(diabetes ~ num_gchild + new_gchild + marital + num_child,\n            data = PhysTibble, family = binomial())\n\nddd <- datadist(PhysTibble)\noptions(datadist = \"ddd\")\n\nmod_Y_lrm <- lrm(diabetes == \"Yes\" ~ num_gchild + new_gchild + marital + num_child,\n                data = PhysTibble, x = TRUE, y = TRUE)\n```\n:::\n\n\n\n\n\n### Tidied Odds Ratio Estimates (Model Y)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(mod_Y, exponentiate = TRUE, conf.int = TRUE, conf.level = 0.90) |>\n  select(term, estimate, se = std.error, \n         low90 = conf.low, high90 = conf.high, p = p.value) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term                 | estimate|    se| low90| high90|     p|\n|:--------------------|--------:|-----:|-----:|------:|-----:|\n|(Intercept)          |    2.672| 0.138| 2.133|  3.358| 0.000|\n|num_gchild           |    0.965| 0.010| 0.949|  0.982| 0.001|\n|new_gchildNo         |    1.043| 0.120| 0.855|  1.270| 0.723|\n|maritalSeperated     |    0.862| 0.122| 0.705|  1.054| 0.222|\n|maritalWidowed       |    1.052| 0.118| 0.867|  1.279| 0.665|\n|maritalNever Married |    1.191| 0.211| 0.847|  1.696| 0.407|\n|num_child            |    0.965| 0.030| 0.918|  1.014| 0.241|\n\n\n:::\n:::\n\n\n\n\n\n### Effects Plot (Model Y)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(summary(mod_Y_lrm, conf.int = 0.90))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Summarizing Fit (Model Y)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod_Y_lrm, conf.int = 0.90) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|                                | Low| High| Diff.| Effect|  S.E.| Lower 0.9| Upper 0.9| Type|\n|:-------------------------------|---:|----:|-----:|------:|-----:|---------:|---------:|----:|\n|num_gchild                      |   3|    8|     5|  0.177| 0.051|     0.093|     0.261|    1|\n|Odds Ratio                      |   3|    8|     5|  1.194|    NA|     1.098|     1.299|    2|\n|num_child                       |   1|    3|     2|  0.071| 0.060|    -0.029|     0.170|    1|\n|Odds Ratio                      |   1|    3|     2|  1.073|    NA|     0.972|     1.186|    2|\n|new_gchild - Yes:No             |   2|    1|    NA|  0.043| 0.120|    -0.155|     0.240|    1|\n|Odds Ratio                      |   2|    1|    NA|  1.043|    NA|     0.856|     1.271|    2|\n|marital - Seperated:Married     |   1|    2|    NA|  0.149| 0.122|    -0.052|     0.350|    1|\n|Odds Ratio                      |   1|    2|    NA|  1.161|    NA|     0.949|     1.419|    2|\n|marital - Widowed:Married       |   1|    3|    NA| -0.051| 0.118|    -0.245|     0.143|    1|\n|Odds Ratio                      |   1|    3|    NA|  0.950|    NA|     0.782|     1.154|    2|\n|marital - Never Married:Married |   1|    4|    NA| -0.175| 0.211|    -0.521|     0.172|    1|\n|Odds Ratio                      |   1|    4|    NA|  0.840|    NA|     0.594|     1.188|    2|\n\n\n:::\n\n```{.r .cell-code}\nmod_Y_lrm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogistic Regression Model\n\nlrm(formula = diabetes == \"Yes\" ~ num_gchild + new_gchild + marital + \n    num_child, data = PhysTibble, x = TRUE, y = TRUE)\n\n                      Model Likelihood       Discrimination    Rank Discrim.    \n                            Ratio Test              Indexes          Indexes    \nObs          2000    LR chi2     22.45       R2       0.016    C       0.571    \n FALSE       1339    d.f.            6      R2(6,2000)0.008    Dxy     0.143    \n TRUE         661    Pr(> chi2) 0.0010    R2(6,1327.6)0.012    gamma   0.144    \nmax |deriv| 6e-08                            Brier    0.219    tau-a   0.063    \n\n                      Coef    S.E.   Wald Z Pr(>|Z|)\nIntercept             -0.9828 0.1379 -7.13  <0.0001 \nnum_gchild             0.0355 0.0102  3.47  0.0005  \nnew_gchild=No         -0.0425 0.1202 -0.35  0.7233  \nmarital=Seperated      0.1491 0.1221  1.22  0.2223  \nmarital=Widowed       -0.0511 0.1181 -0.43  0.6655  \nmarital=Never Married -0.1746 0.2107 -0.83  0.4072  \nnum_child              0.0354 0.0302  1.17  0.2415  \n```\n\n\n:::\n\n```{.r .cell-code}\nglance(mod_Y) |>\n  mutate(df = nobs - df.residual - 1) |>\n  select(AIC, BIC, df, df.residual, nobs) |>\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|    AIC|    BIC| df| df.residual| nobs|\n|------:|------:|--:|-----------:|----:|\n| 2529.7| 2568.9|  6|        1993| 2000|\n\n\n:::\n:::\n\n\n\n\nOur Nagelkerke R2 estimate for Model Y is 0.016, and our C statistic is estimated to be 0.571            \n\n### Confusion Matrix (Model Y)\n\nMy prediction rule for this confusion matrix is that the fitted value of Pr(diabetes = 1) needs to be greater than or equal to 0.65 for me to predict diabetes is 1, and otherwise I predict 0.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresY_aug <- augment(mod_Y, type.predict = \"response\")\n\ncp1 <- cutpointr(data = resY_aug, .fitted, diabetes,  \n                 pos_class = \"Yes\", neg_class = \"No\", \n                 method = maximize_metric, metric = sum_sens_spec) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nAssuming the positive class has lower x values\n```\n\n\n:::\n\n```{.r .cell-code}\ncp1 |> select(direction, optimal_cutpoint, method, sum_sens_spec) |>  \n  gt() |> tab_options(table.font.size = 24) |>  \n  opt_stylize(style = 2, color = \"pink\") \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jgskmyhkjq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jgskmyhkjq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jgskmyhkjq thead, #jgskmyhkjq tbody, #jgskmyhkjq tfoot, #jgskmyhkjq tr, #jgskmyhkjq td, #jgskmyhkjq th {\n  border-style: none;\n}\n\n#jgskmyhkjq p {\n  margin: 0;\n  padding: 0;\n}\n\n#jgskmyhkjq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 24px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 3px;\n  border-top-color: #D5D5D5;\n  border-right-style: solid;\n  border-right-width: 3px;\n  border-right-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 3px;\n  border-bottom-color: #D5D5D5;\n  border-left-style: solid;\n  border-left-width: 3px;\n  border-left-color: #D5D5D5;\n}\n\n#jgskmyhkjq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jgskmyhkjq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jgskmyhkjq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jgskmyhkjq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jgskmyhkjq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n}\n\n#jgskmyhkjq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jgskmyhkjq .gt_col_heading {\n  color: #FFFFFF;\n  background-color: #99195F;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jgskmyhkjq .gt_column_spanner_outer {\n  color: #FFFFFF;\n  background-color: #99195F;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jgskmyhkjq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jgskmyhkjq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jgskmyhkjq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jgskmyhkjq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jgskmyhkjq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jgskmyhkjq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n  vertical-align: middle;\n}\n\n#jgskmyhkjq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jgskmyhkjq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jgskmyhkjq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #FFC6E3;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #FFC6E3;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #FFC6E3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jgskmyhkjq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #5F5F5F;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgskmyhkjq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jgskmyhkjq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jgskmyhkjq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jgskmyhkjq .gt_summary_row {\n  color: #333333;\n  background-color: #FFC6E3;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgskmyhkjq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D5D5D5;\n}\n\n#jgskmyhkjq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jgskmyhkjq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n}\n\n#jgskmyhkjq .gt_grand_summary_row {\n  color: #FFFFFF;\n  background-color: #EF5FA7;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgskmyhkjq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D5D5D5;\n}\n\n#jgskmyhkjq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D5D5D5;\n}\n\n#jgskmyhkjq .gt_striped {\n  background-color: #F4F4F4;\n}\n\n#jgskmyhkjq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D5D5D5;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D5D5D5;\n}\n\n#jgskmyhkjq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jgskmyhkjq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgskmyhkjq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jgskmyhkjq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jgskmyhkjq .gt_left {\n  text-align: left;\n}\n\n#jgskmyhkjq .gt_center {\n  text-align: center;\n}\n\n#jgskmyhkjq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jgskmyhkjq .gt_font_normal {\n  font-weight: normal;\n}\n\n#jgskmyhkjq .gt_font_bold {\n  font-weight: bold;\n}\n\n#jgskmyhkjq .gt_font_italic {\n  font-style: italic;\n}\n\n#jgskmyhkjq .gt_super {\n  font-size: 65%;\n}\n\n#jgskmyhkjq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jgskmyhkjq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jgskmyhkjq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jgskmyhkjq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jgskmyhkjq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jgskmyhkjq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jgskmyhkjq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jgskmyhkjq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jgskmyhkjq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"direction\">direction</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"optimal_cutpoint\">optimal_cutpoint</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sum_sens_spec\">sum_sens_spec</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"direction\" class=\"gt_row gt_left\">&lt;=</td>\n<td headers=\"optimal_cutpoint\" class=\"gt_row gt_right\">0.6491681</td>\n<td headers=\"method\" class=\"gt_row gt_left\">maximize_metric</td>\n<td headers=\"sum_sens_spec\" class=\"gt_row gt_right\">1.122952</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\ncm_Y <- caret::confusionMatrix(\n  data = factor(resY_aug$.fitted >= cp1$optimal_cutpoint),\n  reference = factor(resY_aug$diabetes == \"Yes\"),\n  positive = \"TRUE\")\n\ncm_Y\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction FALSE TRUE\n     FALSE   278  218\n     TRUE   1061  443\n                                         \n               Accuracy : 0.3605         \n                 95% CI : (0.3394, 0.382)\n    No Information Rate : 0.6695         \n    P-Value [Acc > NIR] : 1              \n                                         \n                  Kappa : -0.0924        \n                                         \n Mcnemar's Test P-Value : <2e-16         \n                                         \n            Sensitivity : 0.6702         \n            Specificity : 0.2076         \n         Pos Pred Value : 0.2945         \n         Neg Pred Value : 0.5605         \n             Prevalence : 0.3305         \n         Detection Rate : 0.2215         \n   Detection Prevalence : 0.7520         \n      Balanced Accuracy : 0.4389         \n                                         \n       'Positive' Class : TRUE           \n                                         \n```\n\n\n:::\n:::\n\n\n\n\n\nMy prediction rule is ...\n\nHere are our results, tabulated nicely.\n\nModel\tClassification Rule\tSensitivity\tSpecificity\tPos. Pred. Value\nY\tPredicted Pr(diabetes = 1) >= 0.65 0.670\t0.208\t0.294\n\n\n## Non-Linearity\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(spearman2(diabetes == \"Yes\" ~ num_gchild + new_gchild + marital + num_child,\n            data = PhysTibble))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n\nOur Spearman p2 plot suggests the use of a non-linear term in num_gchild, so we’ll add a restricted cubic spline in num_gchild using 4 knots, which should add 2 degrees of freedom to our initial model.\n\nNext, the num_child variable seems to be a good choice, so we’ll add an interaction between num_child and the main effect of num_gchild, which will add one more degrees of freedom to our model Y.\n\n## Model Z\n\nAs mentioned, our model Z will add 3 degrees of freedom through two non-linear terms, to model Y.\n\n### Fitting Model Z\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_Z <- glm(diabetes ~ num_child + rcs(num_gchild, 4) + new_gchild + \n                num_gchild %ia% num_child + marital,\n            data = PhysTibble, family = binomial())\n\nddd <- datadist(PhysTibble)\noptions(datadist = \"ddd\")\n\nmod_Z_lrm <- lrm(diabetes == \"Yes\" ~ num_child + rcs(num_gchild, 4) + new_gchild + \n                num_gchild %ia% num_child + marital,\n                 data = PhysTibble, x = TRUE, y = TRUE)\n```\n:::\n\n\n\n\n### Tidied Odds Ratio Estimates (Model Z)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(mod_Z, exponentiate = TRUE, conf.int = TRUE, conf.level = 0.90) |>\n  select(term, estimate, se = std.error, \n         low90 = conf.low, high90 = conf.high, p = p.value) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term                           | estimate|    se| low90| high90|     p|\n|:------------------------------|--------:|-----:|-----:|------:|-----:|\n|(Intercept)                    |    2.457| 0.231| 1.685|  3.608| 0.000|\n|num_child                      |    0.885| 0.056| 0.807|  0.970| 0.030|\n|rcs(num_gchild, 4)num_gchild   |    1.053| 0.074| 0.932|  1.189| 0.482|\n|rcs(num_gchild, 4)num_gchild'  |    0.475| 0.464| 0.222|  1.020| 0.109|\n|rcs(num_gchild, 4)num_gchild'' |    5.305| 1.029| 0.975| 28.800| 0.105|\n|new_gchildNo                   |    1.045| 0.120| 0.856|  1.272| 0.714|\n|num_gchild %ia% num_child      |    1.009| 0.005| 1.001|  1.018| 0.070|\n|maritalSeperated               |    0.855| 0.123| 0.699|  1.047| 0.203|\n|maritalWidowed                 |    1.050| 0.118| 0.864|  1.276| 0.683|\n|maritalNever Married           |    1.220| 0.211| 0.867|  1.739| 0.346|\n\n\n:::\n:::\n\n\n\n\n\n### Effects Plot (Model Z)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(summary(mod_Z_lrm, conf.int = 0.90))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Summarizing Fit (Model Z)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod_Z_lrm, conf.int = 0.90) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|                                | Low| High| Diff.| Effect|  S.E.| Lower 0.9| Upper 0.9| Type|\n|:-------------------------------|---:|----:|-----:|------:|-----:|---------:|---------:|----:|\n|num_child                       |   1|    3|     2|  0.152| 0.075|     0.028|     0.276|    1|\n|Odds Ratio                      |   1|    3|     2|  1.164|    NA|     1.028|     1.318|    2|\n|num_gchild                      |   3|    8|     5|  0.285| 0.108|     0.108|     0.463|    1|\n|Odds Ratio                      |   3|    8|     5|  1.330|    NA|     1.114|     1.589|    2|\n|new_gchild - Yes:No             |   2|    1|    NA|  0.044| 0.120|    -0.154|     0.242|    1|\n|Odds Ratio                      |   2|    1|    NA|  1.045|    NA|     0.857|     1.274|    2|\n|marital - Seperated:Married     |   1|    2|    NA|  0.156| 0.123|    -0.046|     0.358|    1|\n|Odds Ratio                      |   1|    2|    NA|  1.169|    NA|     0.955|     1.431|    2|\n|marital - Widowed:Married       |   1|    3|    NA| -0.048| 0.118|    -0.243|     0.146|    1|\n|Odds Ratio                      |   1|    3|    NA|  0.953|    NA|     0.784|     1.158|    2|\n|marital - Never Married:Married |   1|    4|    NA| -0.199| 0.211|    -0.547|     0.149|    1|\n|Odds Ratio                      |   1|    4|    NA|  0.820|    NA|     0.579|     1.160|    2|\n\n\n:::\n\n```{.r .cell-code}\nmod_Z_lrm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogistic Regression Model\n\nlrm(formula = diabetes == \"Yes\" ~ num_child + rcs(num_gchild, \n    4) + new_gchild + num_gchild %ia% num_child + marital, data = PhysTibble, \n    x = TRUE, y = TRUE)\n\n                       Model Likelihood       Discrimination    Rank Discrim.    \n                             Ratio Test              Indexes          Indexes    \nObs           2000    LR chi2     28.70       R2       0.020    C       0.571    \n FALSE        1339    d.f.            9      R2(9,2000)0.010    Dxy     0.143    \n TRUE          661    Pr(> chi2) 0.0007    R2(9,1327.6)0.015    gamma   0.144    \nmax |deriv| 0.0002                            Brier    0.218    tau-a   0.063    \n\n                       Coef    S.E.   Wald Z Pr(>|Z|)\nIntercept              -0.8991 0.2313 -3.89  0.0001  \nnum_child               0.1217 0.0560  2.17  0.0297  \nnum_gchild             -0.0520 0.0739 -0.70  0.4820  \nnum_gchild'             0.7434 0.4637  1.60  0.1089  \nnum_gchild''           -1.6686 1.0288 -1.62  0.1048  \nnew_gchild=No          -0.0441 0.1203 -0.37  0.7142  \nnum_gchild * num_child -0.0091 0.0050 -1.81  0.0701  \nmarital=Seperated       0.1562 0.1227  1.27  0.2031  \nmarital=Widowed        -0.0484 0.1184 -0.41  0.6825  \nmarital=Never Married  -0.1990 0.2114 -0.94  0.3465  \n```\n\n\n:::\n\n```{.r .cell-code}\nglance(mod_Z) |>\n  mutate(df = nobs - df.residual - 1) |>\n  select(AIC, BIC, df, df.residual, nobs) |>\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|    AIC|    BIC| df| df.residual| nobs|\n|------:|------:|--:|-----------:|----:|\n| 2529.4| 2585.4|  9|        1990| 2000|\n\n\n:::\n:::\n\n\n\n\n\n### Confusion Matrix (Model Z)\n\nAs in Model Y, my prediction rule for this confusion matrix is that the fitted value of Pr(diabetes = 1) needs to be greater than or equal to 0.65 for me to predict diabetes is 1, and otherwise I predict 0.\n\nAgain, we augment our PhyTibble data to include predicted probabilities of (diabetes = 1) from Model Z.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresZ_aug <- augment(mod_Z, type.predict = \"response\")\n\ncm_Z <- caret::confusionMatrix(\n  data = factor(resZ_aug$.fitted >= 0.65),\n  reference = factor(resZ_aug$diabetes == \"Yes\"),\n  positive = \"TRUE\")\n\ncm_Z\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction FALSE TRUE\n     FALSE   373  257\n     TRUE    966  404\n                                          \n               Accuracy : 0.3885          \n                 95% CI : (0.3671, 0.4103)\n    No Information Rate : 0.6695          \n    P-Value [Acc > NIR] : 1               \n                                          \n                  Kappa : -0.0867         \n                                          \n Mcnemar's Test P-Value : <2e-16          \n                                          \n            Sensitivity : 0.6112          \n            Specificity : 0.2786          \n         Pos Pred Value : 0.2949          \n         Neg Pred Value : 0.5921          \n             Prevalence : 0.3305          \n         Detection Rate : 0.2020          \n   Detection Prevalence : 0.6850          \n      Balanced Accuracy : 0.4449          \n                                          \n       'Positive' Class : TRUE            \n                                          \n```\n\n\n:::\n:::\n\n\n\n\nHere are our results comparing classification performance by models Y and Z.\n\nModel\tClassification Rule\tSensitivity\tSpecificity\tPos. Pred. Value\nY\tPredicted Pr(HDL_RISK = 1) >= 0.65\t0.670\t0.208\t0.294\nZ\tPredicted Pr(HDL_RISK = 1) >= 0.65\t0.611\t0.279\t0.295\n\n## Validating Models Y and Z\n\nWe will use the validate() function from the rms package to validate our lrm fits.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4323); (valY <- validate(mod_Y_lrm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          index.orig training    test optimism index.corrected  n\nDxy           0.1430   0.1515  0.1228   0.0286          0.1144 40\nR2            0.0155   0.0195  0.0124   0.0070          0.0085 40\nIntercept     0.0000   0.0000 -0.1359   0.1359         -0.1359 40\nSlope         1.0000   1.0000  0.8194   0.1806          0.8194 40\nEmax          0.0000   0.0000  0.0690   0.0690          0.0690 40\nD             0.0107   0.0136  0.0085   0.0051          0.0056 40\nU            -0.0010  -0.0010  0.0003  -0.0013          0.0003 40\nQ             0.0117   0.0146  0.0082   0.0064          0.0053 40\nB             0.2188   0.2189  0.2196  -0.0007          0.2195 40\ng             0.2333   0.2636  0.2118   0.0518          0.1815 40\ngp            0.0522   0.0588  0.0472   0.0116          0.0406 40\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(4324); (valZ <- validate(mod_Z_lrm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          index.orig training    test optimism index.corrected  n\nDxy           0.1429   0.1664  0.1278   0.0386          0.1043 40\nR2            0.0198   0.0277  0.0153   0.0124          0.0074 40\nIntercept     0.0000   0.0000 -0.1688   0.1688         -0.1688 40\nSlope         1.0000   1.0000  0.7506   0.2494          0.7506 40\nEmax          0.0000   0.0000  0.0951   0.0951          0.0951 40\nD             0.0138   0.0196  0.0106   0.0091          0.0048 40\nU            -0.0010  -0.0010  0.0011  -0.0021          0.0011 40\nQ             0.0148   0.0206  0.0094   0.0112          0.0036 40\nB             0.2180   0.2162  0.2192  -0.0031          0.2211 40\ng             0.2842   0.3286  0.2440   0.0846          0.1996 40\ngp            0.0629   0.0722  0.0540   0.0182          0.0447 40\n```\n\n\n:::\n:::\n\n\n\n\n\n### Validated Nagelkerke $R^2$ and $C$ statistics for each model\n\nC = 0.5 + Dxy/2\n\nModel\tValidated R2 Validated C\tAIC\tBIC\tdf\nY\t     0.0085\t      0.5572\t   2529.7\t2568.9\t6\t\nZ\t     0.0074\t      0.5521\t   2529.4\t2585.4\t9\t\n\n\n\n## Final Logistic Regression Model\n\nI prefer Model Y, because of its slightly better validated R2, and validated C statistic, despite the fact that Model Z has a slightly lower AIC and BIC and that Model Z also has a slightly higher positive predictive value. It’s pretty close, though.\n\n### Winning Model's Parameter Estimates\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_Y_lrm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogistic Regression Model\n\nlrm(formula = diabetes == \"Yes\" ~ num_gchild + new_gchild + marital + \n    num_child, data = PhysTibble, x = TRUE, y = TRUE)\n\n                      Model Likelihood       Discrimination    Rank Discrim.    \n                            Ratio Test              Indexes          Indexes    \nObs          2000    LR chi2     22.45       R2       0.016    C       0.571    \n FALSE       1339    d.f.            6      R2(6,2000)0.008    Dxy     0.143    \n TRUE         661    Pr(> chi2) 0.0010    R2(6,1327.6)0.012    gamma   0.144    \nmax |deriv| 6e-08                            Brier    0.219    tau-a   0.063    \n\n                      Coef    S.E.   Wald Z Pr(>|Z|)\nIntercept             -0.9828 0.1379 -7.13  <0.0001 \nnum_gchild             0.0355 0.0102  3.47  0.0005  \nnew_gchild=No         -0.0425 0.1202 -0.35  0.7233  \nmarital=Seperated      0.1491 0.1221  1.22  0.2223  \nmarital=Widowed       -0.0511 0.1181 -0.43  0.6655  \nmarital=Never Married -0.1746 0.2107 -0.83  0.4072  \nnum_child              0.0354 0.0302  1.17  0.2415  \n```\n\n\n:::\n:::\n\n\n\n\n\n### Plot of Effect Sizes for Winning Model\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(summary(mod_Y_lrm, conf.int = 0.90))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Numerical Description of Effect Sizes\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod_Y_lrm, conf.int = 0.90) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|                                | Low| High| Diff.| Effect|  S.E.| Lower 0.9| Upper 0.9| Type|\n|:-------------------------------|---:|----:|-----:|------:|-----:|---------:|---------:|----:|\n|num_gchild                      |   3|    8|     5|  0.177| 0.051|     0.093|     0.261|    1|\n|Odds Ratio                      |   3|    8|     5|  1.194|    NA|     1.098|     1.299|    2|\n|num_child                       |   1|    3|     2|  0.071| 0.060|    -0.029|     0.170|    1|\n|Odds Ratio                      |   1|    3|     2|  1.073|    NA|     0.972|     1.186|    2|\n|new_gchild - Yes:No             |   2|    1|    NA|  0.043| 0.120|    -0.155|     0.240|    1|\n|Odds Ratio                      |   2|    1|    NA|  1.043|    NA|     0.856|     1.271|    2|\n|marital - Seperated:Married     |   1|    2|    NA|  0.149| 0.122|    -0.052|     0.350|    1|\n|Odds Ratio                      |   1|    2|    NA|  1.161|    NA|     0.949|     1.419|    2|\n|marital - Widowed:Married       |   1|    3|    NA| -0.051| 0.118|    -0.245|     0.143|    1|\n|Odds Ratio                      |   1|    3|    NA|  0.950|    NA|     0.782|     1.154|    2|\n|marital - Never Married:Married |   1|    4|    NA| -0.175| 0.211|    -0.521|     0.172|    1|\n|Odds Ratio                      |   1|    4|    NA|  0.840|    NA|     0.594|     1.188|    2|\n\n\n:::\n:::\n\n\n\n\n\nNumber of grandchildren description: If we have two subjects of the same marital status, number of children and new grandchildren status, but a subject 1 has a number of grandchildren of 3 and subject 2 number of grandchildren of 8, then our model estimates that subject 2 will have 1.194 times the odds (90% CI: 1.098,\t1.299\t) that subject 1 has of being at risk of diabetes.\n\n\n### Plot of ROC Curve for Winning Model\n\n\n performance_roc(mod_Y) \n\nplot(performance_roc(mod_Y)) + \n  labs(title = glue(\"Model mod_Y: C statistic = \",\n  round_half_up(as.numeric(performance_roc(mod_Y)),3)))\n  \n\n### Validated $R^2$ and $C$ statistic for Winning Model\n\nAs we saw in Section 9.5.1,\n\nthe validated R2 statistic for Model Y is  0.0085, and\t      \nthe validated C statistic for Model Y is 0.5572.\n\n\n### Nomogram of Winning Model\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(nomogram(mod_Y_lrm, fun = plogis, \n              funlabel = \"Pr(diabetes = 1)\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\n\n\n### Predictions for Two New Subjects\n\nI will create a predicted Pr(diabetes = 1) for two subjects with the same values of num_child (2), new_gchild (Yes) and marital status (Widowed). The first will have a num_gchild of 3, and the second will have a num_gchild of 8.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_subjects <- data.frame(num_child = c(3, 8), num_gchild = c(5, 5),\n             marital = c(\"Widowed\", \"Widowed\"), new_gchild = c(\"Yes\", \"Yes\"))\n\npreds2 <- predict.lm(mod_Y, newdata = new_subjects, \n                     interval = \"prediction\", level = 0.90)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in predict.lm(mod_Y, newdata = new_subjects, interval = \"prediction\", : Assuming constant prediction variance even though model fit is weighted\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(preds2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit       lwr       upr\n1 2.117765 0.4004501 11.199717\n2 1.774273 0.3266542  9.637243\n```\n\n\n:::\n:::\n\n\n\n\n\n# Discusssion\n\n## Answering My Research Questions \n\n### Question 1 (with Answer)\nDoes an increased presence of children and grandchildren directly affect a person’s Systolic Blood Pressure while accounting for marital status?\n\n\nAccording to model A, having a new grandchildren increases the log(sbp) by 0.023 on average when accounting for marital status, number of grandchildren and number of children with a 90% confidence interval around that estimated effect on log(sbp) ranging from (0.0091, 0.038).\n\n\n### Question 2 (with Answer)\nIs there an increased risk for diabetes in those with either less children or grandchildren and how does this change when factoring in a person’s current marital status?\n\nAccording to model Y, the estimated odds ratio of having diabetes is 0.97 for every increased number of grandchildren when adjusting for marital status, number of children and new grandchildren status with a 90% CI 0.95, 0.98.\n\n## Thoughts on Project A\n\n\n### Question 2\nWhat do you wish you’d known at the start of this process that you know now, and why?\n\nWe wish we knew that we would encounter lots of challenging during the review process of the portfolio because we would have designated more time in improving the details of the analysis. \n\n### Question 4\nWhat was the most useful thing you learned while doing the project, and why?\n\nThe most useful thing for us was to being able to use a database not seen during class because it allowed us to have a sense of what it is actually like to approach a public data set for a research question analysis without previous experience.\n\n# Affirmation\n\nI am certain that it is completely appropriate for these data to be shared with anyone, without any conditions. There are no concerns about privacy or security.\n\n# References\n\n1. The Health and Retirement Study (HRS) takes bi-yearly data from people of ages 50 and older which is a longitudinal study supported by the University of Michigan. The intent of the wide range of data it collects is to offer data for multidisciplinary research in the the context of aging.\n2. <https://hrsdata.isr.umich.edu/data-products/2022-hrs-core>\n3. <https://www.nia.nih.gov/research/resource/health-and-retirement-study-hrs>\n\n# Session Information\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxfun::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.4.1 (2024-06-14 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 22631)\n\nLocale:\n  LC_COLLATE=English_United States.utf8 \n  LC_CTYPE=English_United States.utf8   \n  LC_MONETARY=English_United States.utf8\n  LC_NUMERIC=C                          \n  LC_TIME=English_United States.utf8    \n\nPackage version:\n  abind_1.4-5             askpass_1.2.0           backports_1.5.0        \n  base64enc_0.1-3         bayestestR_0.14.0       bigD_0.2.0             \n  bit_4.0.5               bit64_4.0.5             bitops_1.0-8           \n  blob_1.2.4              boot_1.3-30             broom_1.0.7            \n  bslib_0.7.0             cachem_1.1.0            callr_3.7.6            \n  car_3.1-2               carData_3.0-5           cards_0.2.2            \n  caret_7.0-1             caTools_1.18.3          cellranger_1.1.0       \n  checkmate_2.3.1         class_7.3-22            cli_3.6.3              \n  clipr_0.8.0             clock_0.7.1             cluster_2.1.6          \n  coda_0.19-4.1           codetools_0.2-20        colorspace_2.1-0       \n  commonmark_1.9.1        compiler_4.4.1          conflicted_1.2.0       \n  correlation_0.8.5       cowplot_1.1.3           cpp11_0.4.7            \n  crayon_1.5.3            curl_5.2.3              cutpointr_1.2.0        \n  data.table_1.15.4       datasets_4.4.1          datawizard_0.12.3      \n  DBI_1.2.3               dbplyr_2.5.0            DEoptimR_1.1-3         \n  Deriv_4.1.3             diagram_1.6.5           digest_0.6.36          \n  doBy_4.6.22             doParallel_1.0.17       dplyr_1.1.4            \n  dtplyr_1.3.1            e1071_1.7-14            easystats_0.7.3        \n  effectsize_0.8.9        emmeans_1.10.4          estimability_1.5.1     \n  evaluate_0.24.0         fansi_1.0.6             farver_2.1.2           \n  fastmap_1.2.0           fontawesome_0.5.2       forcats_1.0.0          \n  foreach_1.5.2           foreign_0.8-87          Formula_1.2-5          \n  fs_1.6.4                furrr_0.3.1             future_1.34.0          \n  future.apply_1.11.2     gargle_1.5.2            generics_0.1.3         \n  GGally_2.2.1            ggformula_0.12.0        ggplot2_3.5.1          \n  ggrepel_0.9.6           ggridges_0.5.6          ggstats_0.7.0          \n  glmnet_4.1-8            globals_0.16.3          glue_1.8.0             \n  googledrive_2.1.1       googlesheets4_1.1.1     gower_1.0.1            \n  gplots_3.2.0            graphics_4.4.1          grDevices_4.4.1        \n  grid_4.4.1              gridExtra_2.3           gt_0.11.1              \n  gtable_0.3.5            gtools_3.9.5            gtsummary_2.0.2        \n  hardhat_1.4.0           haven_2.5.4             highr_0.11             \n  Hmisc_5.2-2             hms_1.1.3               htmlTable_2.4.2        \n  htmltools_0.5.8.1       htmlwidgets_1.6.4       httr_1.4.7             \n  ids_1.0.1               insight_0.20.4          ipred_0.9-15           \n  isoband_0.2.7           iterators_1.0.14        janitor_2.2.0          \n  jomo_2.7-6              jquerylib_0.1.4         jsonlite_1.8.8         \n  juicyjuice_0.1.0        KernSmooth_2.23.24      knitr_1.48             \n  labeling_0.4.3          labelled_2.13.0         lattice_0.22-6         \n  lava_1.8.0              lifecycle_1.0.4         listenv_0.9.1          \n  lme4_1.1-35.5           lubridate_1.9.3         magrittr_2.0.3         \n  markdown_1.13           MASS_7.3-60.2           Matrix_1.7-0           \n  MatrixModels_0.5-3      memoise_2.0.1           methods_4.4.1          \n  mgcv_1.9-1              mice_3.16.0             microbenchmark_1.4.10  \n  mime_0.12               minqa_1.2.7             mitml_0.4-5            \n  modelbased_0.8.8        ModelMetrics_1.2.2.2    modelr_0.1.11          \n  mosaic_1.9.1            mosaicCore_0.9.4.0      mosaicData_0.20.4      \n  multcomp_1.4-25         munsell_0.5.1           mvtnorm_1.2-5          \n  naniar_1.1.0            nlme_3.1-164            nloptr_2.1.1           \n  nnet_7.3-19             norm_1.0.11.1           numDeriv_2016.8.1.1    \n  opdisDownsampling_1.0.1 openssl_2.2.1           ordinal_2023.12.4.1    \n  pan_1.9                 parallel_4.4.1          parallelly_1.38.0      \n  parameters_0.22.2       patchwork_1.2.0         pbkrtest_0.5.3         \n  pbmcapply_1.5.1         performance_0.12.3      pillar_1.9.0           \n  pkgconfig_2.0.3         plyr_1.8.9              polspline_1.1.25       \n  pracma_2.4.4            prettyunits_1.2.0       pROC_1.18.5            \n  processx_3.8.4          prodlim_2024.06.25      progress_1.2.3         \n  progressr_0.14.0        proxy_0.4-27            ps_1.7.7               \n  purrr_1.0.2             qqconf_1.3.2            qqplotr_0.0.6          \n  quantreg_5.98           R6_2.5.1                ragg_1.3.2             \n  rappdirs_0.3.3          RColorBrewer_1.1-3      Rcpp_1.0.12            \n  RcppEigen_0.3.4.0.0     reactable_0.4.4         reactR_0.6.1           \n  readr_2.1.5             readxl_1.4.3            recipes_1.1.0          \n  rematch_2.0.0           rematch2_2.1.2          report_0.5.9           \n  reprex_2.1.1            reshape2_1.4.4          rlang_1.1.4            \n  rmarkdown_2.27          rms_7.0-0               robustbase_0.99-4-1    \n  ROCR_1.0-11             rpart_4.1.23            rsample_1.2.1          \n  rstudioapi_0.16.0       rvest_1.0.4             sandwich_3.1-0         \n  sass_0.4.9              scales_1.3.0            see_0.9.0              \n  selectr_0.4.2           shape_1.4.6.1           slider_0.3.1           \n  snakecase_0.11.1        SparseM_1.84            splines_4.4.1          \n  SQUAREM_2021.1          stats_4.4.1             stats4_4.4.1           \n  stringi_1.8.4           stringr_1.5.1           survival_3.6-4         \n  sys_3.4.2               systemfonts_1.1.0       textshaping_0.4.0      \n  TH.data_1.1-2           tibble_3.2.1            tidyr_1.3.1            \n  tidyselect_1.2.1        tidyverse_2.0.0         timechange_0.3.0       \n  timeDate_4032.109       tinytex_0.51            tools_4.4.1            \n  twosamples_2.0.1        tzdb_0.4.0              ucminf_1.2.2           \n  UpSetR_1.4.0            utf8_1.2.4              utils_4.4.1            \n  uuid_1.2.1              V8_5.0.1                vctrs_0.6.5            \n  viridis_0.6.5           viridisLite_0.4.2       visdat_0.6.0           \n  vroom_1.6.5             warp_0.2.1              withr_3.0.0            \n  xfun_0.45               xml2_1.3.6              xtable_1.8-4           \n  yaml_2.3.9              zoo_1.8-12             \n```\n\n\n:::\n:::",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}